version: '3.9'
services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    #depends_on:
    #  - db

  #db:
  #  image: mysql:8
  #  restart: always
  #  environment:
  #    MYSQL_DATABASE: ambassador
  #    MYSQL_USER: root
  #    MYSQL_PASSWORD: demoLogin
  #    MYSQL_ROOT_PASSWORD: root
  #  volumes:
  #    - .dbdata:/var/lib/mysql

  